/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import test.PicsOrganizer;
/**
 *
 * @author pipe
 */
public class PicsOrganizerGUI extends javax.swing.JFrame {
    
    String path;
    PicsOrganizer foo;
    
    public PicsOrganizerGUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirLabel = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();
        changepathButton = new javax.swing.JButton();
        organizeButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PicsOrganizer");

        dirLabel.setText("Dir");

        changepathButton.setText("Check");
        changepathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepathButtonActionPerformed(evt);
            }
        });

        organizeButton.setText("Organize");
        organizeButton.setEnabled(false);
        organizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizeButtonActionPerformed(evt);
            }
        });

        statusLabel.setText("ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dirLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(organizeButton)
                                .addGap(47, 47, 47)
                                .addComponent(statusLabel)
                                .addGap(0, 141, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changepathButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirLabel)
                    .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changepathButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizeButton)
                    .addComponent(statusLabel))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changepathButton, dirLabel, pathText});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void organizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizeButtonActionPerformed
        foo.organizePics();
        foo.dirCreator();
        organizeButton.setEnabled(foo.isValidPath());
        
    }//GEN-LAST:event_organizeButtonActionPerformed

    private void changepathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepathButtonActionPerformed
        
        path = pathText.getText().trim();
        if (path.isEmpty()) {
            statusLabel.setText("Not Valid");

        }
        else {
            
            foo = new PicsOrganizer(path); //check if the path exists
            if (!foo.isValidPath()) {
                statusLabel.setText("Not valid path");
            } else {
                foo.getPicsInfo(); // checks if there is any picture in path
                if (!foo.isValidPath()) {
                    statusLabel.setText("No pictures found");
                } else {
                    statusLabel.setText("OK!");
                    organizeButton.setEnabled(foo.isValidPath());
                }
                    
            }
        }
    }//GEN-LAST:event_changepathButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PicsOrganizerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changepathButton;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JButton organizeButton;
    private javax.swing.JTextField pathText;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
