/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import test.PicsOrganizer;
/**
 *
 * @author pipe
 */
public class PicsOrganizerGUI extends javax.swing.JFrame {
    
    String path;
    
    public PicsOrganizerGUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirLabel = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();
        changepathButton = new javax.swing.JButton();
        organizeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PicsOrganizer");

        dirLabel.setText("Dir");

        changepathButton.setText("...");
        changepathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepathButtonActionPerformed(evt);
            }
        });

        organizeButton.setText("Organize");
        organizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(organizeButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changepathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirLabel)
                    .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changepathButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(organizeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changepathButton, dirLabel, pathText});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void organizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizeButtonActionPerformed
        PicsOrganizer foo = new PicsOrganizer(path);   
        foo.getPicsInfo();  //class methods have to be called in this order!
        foo.organizePics();
        foo.debPics();
        foo.dirCreator();
    }//GEN-LAST:event_organizeButtonActionPerformed

    private void changepathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepathButtonActionPerformed
        path = pathText.getText();
    }//GEN-LAST:event_changepathButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PicsOrganizerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changepathButton;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JButton organizeButton;
    private javax.swing.JTextField pathText;
    // End of variables declaration//GEN-END:variables
}
